"""add rate_limit_logs table

Revision ID: 33cfbcc8a424
Revises: 519f49654987
Create Date: 2026-07-30 01:57:12.936031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cfbcc8a424'
down_revision = '519f49654987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_lookup', ['client_ip', 'endpoint', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_lookup')

    op.drop_table('rate_limit_logs')
    # ### end Alembic commands ###
