"""add constraints to models

Revision ID: 519f49654987
Revises: 762bdda561ec
Create Date: 2026-07-26 16:58:54.713996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519f49654987'
down_revision = '762bdda561ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint('customers_email_key', ['email'])

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_provider_reference', ['provider', 'provider_reference'])

    op.create_check_constraint('check_valid_email_format', 'customers', "email LIKE '%@%.%'")
    op.create_check_constraint('check_positive_amount', 'payment_attempts', "amount > 0")
    op.create_check_constraint('check_valid_status', 'payment_attempts', "status IN ('PENDING', 'SUCCESS', 'FAILED', 'DECLINED')")
    op.create_check_constraint('check_valid_provider', 'payment_attempts', "provider IN ('FAWRY', 'STRIPE', 'PAYPAL')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_valid_provider', 'payment_attempts', type_='check')
    op.drop_constraint('check_valid_status', 'payment_attempts', type_='check')
    op.drop_constraint('check_positive_amount', 'payment_attempts', type_='check')
    op.drop_constraint('check_valid_email_format', 'customers', type_='check')
    
    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_provider_reference', type_='unique')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_email_key', type_='unique')

    # ### end Alembic commands ###
