"""add idempotency key to payments

Revision ID: b1c65abdb657
Revises: d9d220c209c5
Create Date: 2026-07-25 19:50:21.301230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c65abdb657'
down_revision = 'd9d220c209c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['idempotency_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
