"""set customer foreign key on delete set null

Revision ID: d59501e4cafe
Revises: 9deee1f3e031
Create Date: 2026-07-27 13:38:19.927572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59501e4cafe'
down_revision = '9deee1f3e031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments_history', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('payments_history_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_history_customer_id_fkey'), 'customers', ['customer_id'], ['id'])
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
